# currently a quarto project is required for metadata or brand extensions to work
project:
  type: website

callout-appearance: simple

website:
  title: "SGSSS Brand YML"
  page-navigation: true
  navbar:
    pinned: false

    right:
      - text: "Placeholder Text"

  sidebar:
    style: "docked"
    contents:
      - href: example.qmd
        text: "Example Page"
      - href: todo_notes.qmd
      - href: notes.qmd

format:
  html:
    toc: true
