---
title: SGSSS Brand Extension Example
---

## brand.yml extension

Some **bold** and **italics**. Here is [a link](https://example.com).


### Callouts

:::{.callout-note title="Note"}
Example note callout.
:::

:::{.callout-warning title="Warning"}
Example warning callout.
:::

:::{.callout-important title="Important"}
Example important callout.
:::

:::{.callout-tip title="Tip"}
Example tip callout.
:::

:::{.callout-caution}
Example caution callout with no title.
:::


### Instructions

Below are instructions:

::: instructions

Testing testing 1 2 3 4

:::

### Code
  
Here is some inline code: `def foo(x): return x`{.python} and `y`{.python} and `z`{.python}.

Here is a code block:

```{r}
#| echo: true
fibonacci <- function(n) {
  if (n <= 0) {
    return(NULL)
  } else if (n == 1) {
    return(0)
  } else if (n == 2) {
    return(1)
  } else {
    return(fibonacci(n - 1) + fibonacci(n - 2))
  }
}
```

### TODOS and notes

- Despite docs showing defaults>quarto>format as option, looks like none of the key HTML format options work with brand extension at present.
- Currently unable to set different light/dark navbar colours (see [this GitHub issue](https://github.com/posit-dev/brand-yml/issues/52))

**Quick**: 

- [x] Able to set coding colourscheme via brand?
  - No. Theme and CSS Quarto default's don't work with brand extension it seems.

**Longer-term**:

- [ ] btn-code-copy-color-active doesn't work when setting 'defaults'.
  - (Also need to customise it's regular colour.)
- [ ] Test whether can package scss can load for dark theme to address current limitations

#### Dark theme file

- [ ] Gray-300 gets used for callout border in light *and* dark. Replace in dark with gray-700 or 800
- [ ] Fix nav bar
